# Generated by Django 4.2.4 on 2023-10-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='fecha_baja',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='fecha_baja',
        ),
        migrations.AddField(
            model_name='doctor',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
