# Generated by Django 4.2.6 on 2023-11-18 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_persona2_alter_especialidad_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='turno',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.especialidad'),
        ),
    ]
