# Generated by Django 4.2.6 on 2023-11-25 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_turno_especialidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='edad',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
